basePath: /v1
host: localhost:8080
info:
  contact:
    email: oogiriminister@gamil.com
    name: murasame29
  description: This is a PDD-GitHub-Go-Backend API server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: PDD-GitHub-Go-Backend GithubAPI
  version: 0.0.1
paths: {}
swagger: "2.0"
